version: "3"

services:
    nodeserver:
        build: ./server
        ports:
            - "8080:8080"
    frontend:
        build: ./web-client
        ports:
            - "8081:8081"
        volumes:
            - static-content:/home/
    # mobile:
    #     build: ./mobile-client
    #     volumes:
    #       - static-content:/home/android/
volumes:
     static-content: