version: '3.3'

services:
  api:
    build: ./api
    restart: always
    ports: 
      - "3000:3000"
    volumes: 
      - ./api:/api
      - /api/node_modules
    networks:
      - webappnetwork
  client_web:
    build: ./web
    restart: always
    ports:
    - 8080:8080
    volumes:
    - ./web:/web
    - /web/node_modules
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge
